name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Azure Container Registry Username
        run: |
          echo "Azure Host: ${{ secrets.AZURE_VM_HOST }}"
      - name: Print Azure Container Registry Password
        run: | 
          echo "Azure Username: ${{ secrets.AZURE_VM_USERNAME }}"
      - name: Print Azure VM Host
        run: | 
          echo "Azure Password: ${{ secrets.AZURE_VM_PASSWORD }}"
      - name: Copy files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: .
          target: /home/leo123/rag_test
#      - name: SSH into Azure VM and stop FastAPI app
#          uses: appleboy/ssh-action@master
#          with:
#            host: ${{ secrets.AZURE_VM_HOST }}
#            username: ${{ secrets.AZURE_VM_USERNAME }}
#            password: ${{ secrets.AZURE_VM_PASSWORD }}
#            script: |
#              cd /home/leo123/rag_test
#              if pgrep uvicorn; then
#                echo "FastAPI is running, stopping it..."
#                pkill -f uvicorn
#              else
#                echo "FastAPI is not running"
#              fi
      - name: SSH into Azure VM and update requirements
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd /home/leo123/rag_test
            echo "Updating requirements..."
            source venv/bin/activate
            pip install -r requirements.txt
      - name: SSH into Azure VM and update requirements and run FastAPI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd /home/leo123/rag_test
            echo "Starting FastAPI..."
            source venv/bin/activate
            uvicorn main:app --host 0.0.0.0 --port 8080 --reload
