name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Azure Container Registry Username
        run:
          echo "ACR Username: ${{ secrets.ACR_USERNAME }}"
      - name: Print Azure Container Registry Password
        run:
          echo "ACR Password: ${{ secrets.ACR_PASSWORD }}"
      - name: Print Azure VM Host
        run:
          echo "Azure VM Host: ${{ secrets.AZURE_VM_HOST }}"
      - name: Copy files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: .
          target: /path/to/destination/folder/on/azure/vm
