name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Azure Container Registry Username
        run: |
          echo "Azure Host: ${{ azure_secrets.AZURE_VM_HOST }}"
      - name: Print Azure Container Registry Password
        run: | 
          echo "Azure Username: ${{ azure_secrets.AZURE_VM_USERNAME }}"
      - name: Print Azure VM Host
        run: | 
          echo "Azure Password: ${{ azure_secrets.AZURE_VM_PASSWORD }}"
      - name: Copy files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ azure_secrets.AZURE_VM_HOST }}
          username: ${{ azure_secrets.AZURE_VM_USERNAME }}
          password: ${{ azure_secrets.AZURE_VM_PASSWORD }}
          source: .
          target: /path/to/destination/folder/on/azure/vm
